package com.brightkut.walley_v2.model.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "transaction")
public class Transaction {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String transactionId;

    @DynamoDBAttribute
    private String type;

    @DynamoDBAttribute
    private BigDecimal amount;

    @DynamoDBAttribute
    private Date date;

    @DynamoDBAttribute
    private String userId;
}
